

openapi: 3.0.0
info:
  version: 1.0.1
  title: Geek Quote API
  description: An API to retrieve quotes from famous geeks.

servers:
- url: https://geek-quote-api.vercel.app
  description: Vercel server
- url: https://localhost:8080
  description: Local server

paths:
  /v1/quotes:
    get:
      summary: Get all quotes
      responses:
        '200':
          description: A list of all quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '404':
          description: No quotes found
  /v1/quote:
    get:
      summary: Get a single quote
      responses:
        '200':
          description: A single quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Quote not found
  /v1/quote/{count}:
    get:
      summary: Get a specific number of quotes
      parameters:
        - name: count
          in: path
          description: Number of quotes to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '404':
          description: No quotes found
  /v1/quote/filter/known:
    get:
      summary: Get a single quote from a known author
      responses:
        '200':
          description: A single quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Quote not found
  /v1/quote/filter/known/{count}:
    get:
      summary: Get a specific number of quotes from known authors
      parameters:
        - name: count
          in: path
          description: Number of quotes to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '404':
          description: No quotes found
  /v1/quote/filter/{keyword}:
    get:
      summary: Get a single quote that matches a keyword
      parameters:
        - name: keyword
          in: path
          description: Keyword to search for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Quote not found
  /v1/quote/filter/all/{keyword}:
    get:
      summary: Get all quotes that match a keyword
      parameters:
        - name: keyword
          in: path
          description: Keyword to search for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of all quotes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '404':
          description: No quotes found
components:
  schemas:
    Quote:
      type: object
      properties:
        id:
          type: integer
        author:
          type: string
        quote:
          type: string
        source:
          type: string